### PR TITLE
Update penthouse version

### PR DESCRIPTION
**Pull request by bsteinborn**

### CODE REVIEW

**Comment by pocketjoso** [comment]
@fatso83 if you don't have time to merge these PR's - perhaps give me privileges and I can sort it out. Cheers

**Comment by fatso83** [comment]
Forgot about it! Merged!

**Comment by pocketjoso** [comment]
..meanwhile, `Penthouse` has already gone up to `0.7.0`. ;) Time for another bump? :)

**Comment by fatso83** [comment]
I have been working on #12 for the last hour, and there I have made the Penthouse version a bit more loose to avoid such tiny updates. Everything Penthouse < 1.0 is now ok. That means it should be up to date with all future version until a breaking interface change comes along.

**Comment by bsteinborn** [comment]
Cool. Thanks.

**Pull request merged**
