### PR TITLE
add error skipping

### PR DESCRIPTION
**Pull request by eparisio**
Add a parameter to skip errors and show warning/error on fail

* skipErrors: continue the process even on connection fail/other errors

Add this controller for multi task processes with different processors, in case someone need to build-up other tasks without penthouse,

Added "Done!" message.

### CODE REVIEW

**Comment by fatso83** [comment]
Thanks for your work. Would you mind squashing it down to one commit, please? 

`git rebase -i origin/master`

**Comment by fatso83** [comment]
I have no idea what you mean by this:

> Add this controller for multi task processes with different processors, in case someone need to build-up other tasks without penthouse

Is this actually related to your code?

**Comment by eparisio** [comment]
hi yes we have a task (and probably not only us) that execute different command in this way:

> grunt.registerTask('cleanAll', [ 'clean:css','clean:initJsMin', 'clean:initJsLibGen' ]);
> grunt.registerTask('penthouseAll', [ 'penthouse:category','penthouse:product', 'replace:penthouse:']);
> grunt.registerTask('prodJs', [ 'clean:initJsLibGen',  'uglify:concatLibs', 'uglify:concatApps', 'clean:initJsMin', 'uglify:prod' ]);

> grunt.registerTask('prod', [ 'css', 'penthouseAll', 'prodJs' ]);

and there is the possibility that we want to run the command `grunt prod` and the task should procede until the end even if one of the pages is not reachable due to any problem (server or page code).
In any case i have added the error message in case of failure.

if you have some improvement feel free to do it :smiley:

**Comment by fatso83** [comment]
I have been way too busy so totally forgot about this. Sorry about that!

There were some issues with your merge that made me put this into the backlog. I fixed them now, but you might want to keep them in mind later on in case you want to up your open source foo :smiley: 

- add tests that [shows that the functionality you added is actually working](https://github.com/fatso83/grunt-penthouse/commit/bf971fc26bf704f62172e09e4758bebb4cb7cbdf)
- Document the added functionality in the README
- Squash smaller commits into a single commit with a meaningful commit message ([this article](http://makandracards.com/makandra/527-squash-several-git-commits-into-a-single-commit) is the easiest way)
- Run the linting tool, if there is one

The last point is really on me: I have now added a pre-commit hook in the master branch so that all commits will trigger linting and tests. So no loose curly brackets from now on.

I have now merged your work into the main branch, but as I rebased your changes the commit ids do not match, so it seems as if it is not there, but _it really is_ :smile:

**Pull request closed without merging**
